### ISSUE TITLE
start 0.4.2 docker failed

### ISSUE THREAD

**Issue by lcgogo** [openworklabs/filecoin-docker#18]
2020-07-28T05:01:48.799Z	WARN	chainstore	store/store.go:143	no previous chain state found
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/go/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.AfterGenesisSet: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: genesis func failed: decoding block failed: unmarshaling t.ElectionProof pointer: cbor input had wrong number of fields

**Comment by symanovich-a** [comment]
Hi @lcgogo, could you try openworklabs/lotus:master ?

**Comment by ArseniiPetrovich** [comment]
Closed because this error was fixed in latest releases.

**Comment by ArseniiPetrovich** [comment]
Feel free to reopen if necessary.

**Comment by lcgogo** [comment]
Run new release is ok for me now. Thanks.
